// scripts/compile-fonts.js
import figlet from 'figlet'
import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FONTS_DIR = resolve(__dirname, '../src/fonts')

// Curated font list
const FONTS = [
  'Standard',
  'Big',
  'Small',
  'Banner',
  'Block',
  'Doom',
  'Slant',
  'Shadow',
  'Isometric1',
  'Mini',
  'Short',
  'Thin',
  'Bubble',
  'Digital',
  'Graffiti',
  'ANSI Regular',
  'Cybermedium',
  'Rectangles'
]

// Characters to include in font data
const CHARS = ' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~'

// Get list of all available figlet fonts for validation
function getFigletFonts() {
  return new Promise((resolve, reject) => {
    figlet.fonts((err, fonts) => {
      if (err) reject(err)
      else resolve(fonts)
    })
  })
}

function extractFont(fontName) {
  return new Promise((resolve, reject) => {
    const charMap = {}
    let height = 0
    let errors = 0

    let pending = CHARS.length
    for (const char of CHARS) {
      figlet.text(char, { font: fontName }, (err, result) => {
        if (err) {
          errors++
          pending--
          if (pending === 0) resolve({ charMap, height, errors })
          return
        }
        const lines = result.split('\n')
        while (lines.length && lines[lines.length - 1].trim() === '') {
          lines.pop()
        }
        if (lines.length > height) height = lines.length
        charMap[char] = lines
        pending--
        if (pending === 0) resolve({ charMap, height, errors })
      })
    }
  })
}

async function compileFont(fontName, availableFonts) {
  // Validate font exists in figlet
  if (!availableFonts.includes(fontName)) {
    const suggestion = availableFonts.find(f => f.toLowerCase() === fontName.toLowerCase())
    const hint = suggestion ? ` Did you mean "${suggestion}"?` : ''
    throw new Error(`Font "${fontName}" not found in figlet.${hint} Run: node -e "import('figlet').then(f => f.default.fonts((e,r) => console.log(r.join('\\n'))))" to list all available fonts.`)
  }

  console.log(`Compiling: ${fontName}`)
  const { charMap, height, errors } = await extractFont(fontName)

  // Validate we got usable output
  const charCount = Object.keys(charMap).length
  if (charCount === 0) {
    throw new Error(`Font "${fontName}" produced no character data. It may be incompatible.`)
  }
  if (charCount < 26) {
    console.warn(`  ⚠ Warning: Font "${fontName}" only rendered ${charCount}/${CHARS.length} characters (${errors} errors). Some characters may show as blank.`)
  }

  for (const char of Object.keys(charMap)) {
    while (charMap[char].length < height) {
      charMap[char].push('')
    }
  }

  const safeName = fontName.toLowerCase().replace(/\s+/g, '-')
  const moduleContent = `// Pre-compiled font: ${fontName}\n// Generated by ascii-flair compile-fonts.js — do not edit\nexport default ${JSON.stringify({ name: fontName, height, chars: charMap })}\n`

  const outPath = resolve(FONTS_DIR, `${safeName}.js`)
  writeFileSync(outPath, moduleContent, 'utf8')
  console.log(`  → src/fonts/${safeName}.js`)
}

async function main() {
  if (!existsSync(FONTS_DIR)) {
    mkdirSync(FONTS_DIR, { recursive: true })
  }

  const availableFonts = await getFigletFonts()
  console.log(`figlet has ${availableFonts.length} fonts available.\n`)

  const fontEntries = []

  for (const font of FONTS) {
    try {
      await compileFont(font, availableFonts)
      const safeName = font.toLowerCase().replace(/\s+/g, '-')
      fontEntries.push({ name: font, file: safeName })
    } catch (err) {
      console.warn(`  ⚠ Skipping ${font}: ${err.message}`)
    }
  }

  const registryContent = `// Auto-generated font registry — do not edit\nexport const FONT_REGISTRY = ${JSON.stringify(
    Object.fromEntries(fontEntries.map(f => [f.file, f.name]))
  , null, 2)}\n\nexport const FONT_NAMES = ${JSON.stringify(fontEntries.map(f => f.file))}\n`

  writeFileSync(resolve(FONTS_DIR, '_registry.js'), registryContent, 'utf8')
  console.log(`\nCompiled ${fontEntries.length} fonts.`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
